version: "2"
services:
  backend:
    restart: always
    environment:
      - LOGGING_LEVEL=WARNING
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
